### PR TITLE
meteorhacks:flow-router to kadira:flow-router

### PR DESCRIPTION
**Pull request by lsunsi**
Just changed the soft dependencies to kadira:flow-router in order to reflect the recent updates.

### CODE REVIEW

**Comment by zimme** [comment]
This is good, but changing meteorhacks:flow-router breaks backwards compatibility and I'm not up for releasing a new major version. Please update the PR to add kadira:flow-router and not replace meteorhacks:flow-router.

Also i think i read that flow 2.0 doesnt support Reactivecurrent which i believe i rely upon.

**Comment by zimme** [comment]
kadira:flow-router should take precedence over meteorhacks:flow-router.

**Comment by lsunsi** [comment]
I don't think you should care about keeping compatibility since meteorhacks:flow-router is being deprecated by kadira. Also, it seems you only use current() with watchPathChange(), which is the 2.0 way of using reactiveCurrent(), so I doesn't seem to be a problem.

**Comment by zimme** [comment]
I see your point but still, semantic versioning dictates major version bump for breaking changes. I'll have to think about this until saturday when Im getting home from my vacation. But Im leaning against supporting all routers and doing a minor version bump. But feel free to convince me otherwise. Im open for releasing new major version with iron:router and kadira:flow-router.

Maybe @arunoda have a thought or two on the subject?

**Comment by zimme** [comment]
Also we will need to update the tests to "mock" kadira:flow-router too/instead

**Comment by arunoda** [comment]
I think since this is a weak dependency try to depend for both `meteorhacks:flow-router` and `kadira:flow-router`. Then select what ever the FlowRouter version app have.

With that, you can do a minor release.

**Comment by lsunsi** [comment]
I agree that doing a minor version bump with both meteorhacks and kadira flow-router support is probably the best way to go. I'm just pointing out that when you say 'support all routers', you are thinking about meteorhacks and kadira flow-router as different ones. That's the part I disagree.

In any case, the minor version release might be the best way to go, keeping in mind to drop meteorhacks:flow-router as a part of a future major release.

**Comment by zimme** [comment]
@lsunsi, up for changing this PR to reflect the changes talked about here? Otherwise I'll take care of it saturday/sunday

**Comment by zimme** [comment]
@arunoda is meteorhacks:flow-router getting a version bump to 2.0.0 which uses and implies kadira:flow-router? like the way I did with zimme:iron-router-active?

**Comment by arunoda** [comment]
No. It won't getting any update. Why you wanna have that.

**Comment by zimme** [comment]
Did say I wanted it ;) just wondered. It would affect how I depend on it,  meteorhacks:flow-router@1.0.0 || 2.0.0 for example. But now I know it's not needed :) :+1:

**Comment by lsunsi** [comment]
I would do it, but I can't do it right away.
Probably best to wait til the weekend and see what you come up with haha.

**Comment by zimme** [comment]
No problem at all, thanks for the effort anyways. Nice to know ppl care about things you've done :+1:

**Comment by zimme** [comment]
Closing this as I've fixed this. Tracking in #36. Just gonna have a stab at #35 before release.

**Pull request closed without merging**
