### PR TITLE
added support for flowrouter-ssr

### PR DESCRIPTION
**Pull request by TimBroddin**
Made a quick fix to allow the usage of flow-router-ssr. Don't know Coffeescript too wel, but it seems to work.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zimme/meteor-active-route/pull/50" target="_blank">ReviewNinja

**Comment by zimme** [comment]
I'm out traveling, I'll try and get to this as soon as possible. Hopefully I can spare an hour or so in a few days =)

**Comment by marcdibold** [comment]
+1

**Comment by fvpDev** [comment]
+1

**Comment by zimme** [comment]
Added in 2.3.3-rc.2

**Pull request closed without merging**
