### PR TITLE
Prepare to merge with ostrio:iron-router-helpers

### PR DESCRIPTION
**Pull request by dr-dimitru**
- Implement the same way to path tests by path includes, as it was in
`ostrio:iron-router-helpers`
- Semver update

### CODE REVIEW

**Comment by zimme** [comment]
I see where you're going with this... but the main reason I only do string match for this form is because of performance, and that only {{isActiveRoute regex="omglol"}} do regex matches.

If there's a way we can do regex matching for the for {{isActiveRoute 'omglol'}} only if the string contains some regex things that would make this better.

**Comment by dr-dimitru** [comment]
@zimme I've just tried, no luck, doesn't fits our needs

**Comment by zimme** [comment]
I'm going to have to think about this use case a bit. I'm wondering what most users will need, exact string matching or regex matching. I feel the helpers should default to the most used case.

This might end up being something that keeps us from actually merging packages :/

**Comment by zimme** [comment]
And I think that's ok because then there's a specific reason for having two different packages

**Comment by dr-dimitru** [comment]
Closing merging on this point?

**Comment by zimme** [comment]
See #29, maybe this will be enough for the merge to go through?

**Comment by zimme** [comment]
I've added a new option `regex` with version `2.1.0`, which makes `{{isActiveRoute '^home'}}` do RegExp matching.

If you use, imply and do `ActiveRoute.config({ regex: true });` in you package it should be enough to make it work as before. For users which switch over to using my package directly, they will just have to set that option manually in their app to get the desired behaviour.

If you don't feel this is enough you can close this PR, leaving the two packages separate (which is fine).

**Comment by zimme** [comment]
I'll close this now @dr-dimitru, just @mention me here if you think we should re-open this and keep going with the merging effort.

**Pull request closed without merging**
