### PR TITLE
Rewrite in es2015

### PR DESCRIPTION
**Pull request by zimme**
This is where the progress of the es2015 rewrite is being tracked.

### CODE REVIEW

**Comment by Paku-** [comment]
@zimme 
Are you going to finish the Meteor 1.4 compatible code ??

**Comment by zimme** [comment]
I've been meaning to re-write this package in es2015 instead of coffeescript because it would be easier for people from the community to take over maintenance of this. I don't use Meteor in my day to day any more so that's why this isn't done yet.

I've created an organization activeroute on Meteor for the rewrite where packages can be published under (`activeroute:core`, `activeroute:blaze`, etc.).

I've also created a github organization for a community driven version if this package, https://github.com/meteor-activeroute. Under this organization I've created a few repos for how I see the new structure of the package(s).

I've decided to split out the route and view helpers layer from the core logic to make it be more open for adding new router/view layers and people using a specific router don't get extra logic for a router they don't even use.

I have no idea when this will be done, because I've had a hard time finding the time, but if there are any people from the community who wanna take this on I've more than happy to give you access to the organizations to be able to do this work.

**Comment by Paku-** [comment]
The problem is, I have no idea how the Meteor packages work. But can imagine  the code itself is not so complicated.

**Comment by zimme** [comment]
This is also one reason I wanna do this re-write and release a new major version and under a new organization. The package system has gone thought quite big changes during since 1.2 and even though it's backwards compatible it's a mess trying to figure out how to support the old implicit export and the new explicit import system.

So the new code I've started on only support the newer way of doing things.

**Comment by zimme** [comment]
I'm closing this PR because I've decided to split the package in smaller parts as I'm doing the re-write, to make it more extendable. It's also gonna live under it's own github org where the community can take over maintenance it they feel like it.

**Comment by zimme** [comment]
@Paku- I've published an alpha of the new packages. [activeroute:core], [activeroute:blaze], [activeroute:flow-router] and [activeroute:iron-router].

[activeroute:core]: https://github.com/meteor-activeroute/core
[activeroute:blaze]: https://github.com/meteor-activeroute/blaze
[activeroute:flow-router]: https://github.com/meteor-activeroute/flow-router
[activeroute:iron-router]: https://github.com/meteor-activeroute/iron-router

**Comment by Paku-** [comment]
I saw your other conversation. Thank you. Will look into it.

**Pull request closed without merging**
